import React from 'react';
import { AlertTriangleIcon, LoaderIcon, DownloadIcon, TrashIcon } from './icons';
import { ImageSize } from '../App';

interface ImageDisplayProps {
  imageUrl: string | null;
  loading: boolean;
  error: string | null;
  selectedSize: ImageSize;
  onClearImage: () => void;
  countdown: number | null;
}

const ImageDisplay: React.FC<ImageDisplayProps> = ({ imageUrl, loading, error, selectedSize, onClearImage, countdown }) => {
  const aspectRatioClass = selectedSize === 'YouTube (16:9)' ? 'aspect-video' : 'aspect-square';

  const handleDownload = () => {
    if (!imageUrl) return;
    const link = document.createElement('a');
    link.href = imageUrl;
    link.download = 'gerado-por-pika.png';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className={`w-full max-w-2xl ${aspectRatioClass} bg-gray-900/50 rounded-2xl flex items-center justify-center p-2 overflow-hidden transition-all duration-300 relative group`}>
      {loading && (
        <div className="flex flex-col items-center justify-center text-gray-400 text-center">
          <LoaderIcon />
          <p className="mt-4 text-lg font-semibold tracking-wide">Gerando sua obra de arte...</p>
          {countdown !== null && countdown > 0 && (
             <p className="mt-1 text-sm text-gray-500">
                Tempo estimado: <span className="font-semibold text-gray-400">{countdown}s</span>
             </p>
          )}
           {countdown !== null && countdown <= 0 && (
             <p className="text-sm text-gray-500 mt-1">Quase pronto...</p>
           )}
        </div>
      )}
      {error && (
        <div className="flex flex-col items-center justify-center text-red-400 text-center p-4">
          <AlertTriangleIcon />
          <p className="mt-4 font-semibold text-lg">Oops! Algo deu errado.</p>
          <p className="text-sm text-red-500 mt-1">{error}</p>
        </div>
      )}
      {!loading && !error && imageUrl && (
        <>
          <img
            src={imageUrl}
            alt="Generated by AI"
            className="object-contain w-full h-full rounded-lg opacity-0 animate-fade-in"
          />
          <div className="absolute top-4 right-4 flex flex-col gap-3 opacity-0 group-hover:opacity-100 transition-opacity duration-300">
            <button
              onClick={handleDownload}
              className="p-2 bg-gray-900/60 backdrop-blur-sm rounded-full text-gray-200 hover:text-white hover:bg-gray-800/80 transition-colors"
              aria-label="Baixar imagem"
            >
              <DownloadIcon />
            </button>
            <button
              onClick={onClearImage}
              className="p-2 bg-gray-900/60 backdrop-blur-sm rounded-full text-gray-200 hover:text-white hover:bg-red-600/80 transition-colors"
              aria-label="Remover imagem"
            >
              <TrashIcon />
            </button>
          </div>
        </>
      )}
      <style>{`
        @keyframes fade-in {
          from { opacity: 0; }
          to { opacity: 1; }
        }
        .animate-fade-in {
          animation: fade-in 0.7s ease-in-out forwards;
        }
      `}</style>
    </div>
  );
};

export default ImageDisplay;